---
- name: Set Common Configuration
  hosts: all
  become: true
  roles:
    - common

- name: Configure Master Node
  hosts: master_node
  roles:
    - master

- name: Configure Worker Nodes
  hosts: worker_nodes
  roles:
    - worker

- name: Install Spack Dependencies
  hosts: all
  roles:
    - spack
